"""Cambiar fecha_desde y fecha_hasta de Date a DateTime en historico_titulares_expediente

Revision ID: 0d6742443660
Revises: bf66f512eaf4
Create Date: 2026-02-07 08:23:15.949626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6742443660'
down_revision = 'bf66f512eaf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_titulares_expediente', schema=None) as batch_op:
        batch_op.alter_column('fecha_desde',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               comment='Timestamp inicio vigencia. TIMESTAMP permite múltiples cambios/día para corrección de errores',
               existing_comment='Fecha inicio vigencia de este titular. Para registro INICIAL = fecha creación expediente',
               existing_nullable=False)
        batch_op.alter_column('fecha_hasta',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               comment='Timestamp fin vigencia. NULL = titular actual vigente. NOT NULL = titular histórico',
               existing_comment='Fecha fin vigencia. NULL = titular actual vigente. NOT NULL = titular histórico',
               existing_nullable=True)
        batch_op.alter_column('motivo',
               existing_type=sa.VARCHAR(length=50),
               comment='Motivo del cambio: INICIAL, VENTA, HERENCIA, FUSION, ESCISION, CAMBIO_TITULAR, OTRO',
               existing_comment='Motivo del cambio: INICIAL, VENTA, HERENCIA, FUSION, ESCISION, OTRO',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_titulares_expediente', schema=None) as batch_op:
        batch_op.alter_column('motivo',
               existing_type=sa.VARCHAR(length=50),
               comment='Motivo del cambio: INICIAL, VENTA, HERENCIA, FUSION, ESCISION, OTRO',
               existing_comment='Motivo del cambio: INICIAL, VENTA, HERENCIA, FUSION, ESCISION, CAMBIO_TITULAR, OTRO',
               existing_nullable=True)
        batch_op.alter_column('fecha_hasta',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               comment='Fecha fin vigencia. NULL = titular actual vigente. NOT NULL = titular histórico',
               existing_comment='Timestamp fin vigencia. NULL = titular actual vigente. NOT NULL = titular histórico',
               existing_nullable=True)
        batch_op.alter_column('fecha_desde',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               comment='Fecha inicio vigencia de este titular. Para registro INICIAL = fecha creación expediente',
               existing_comment='Timestamp inicio vigencia. TIMESTAMP permite múltiples cambios/día para corrección de errores',
               existing_nullable=False)

    # ### end Alembic commands ###
