"""Fix tabla_metadata structure - Issue #85

Revision ID: 0f6a72b443e5
Revises: 12c75207263b
Create Date: 2026-02-07 06:16:22.977491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f6a72b443e5'
down_revision = '12c75207263b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autorizados_titular', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('autorizados_titular_autorizado_entidad_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('autorizados_titular_titular_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['titular_entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'entidades', ['autorizado_entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('documentos_expediente_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'expedientes', ['expediente_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('documentos_proyecto', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('documentos_proyecto_documento_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_documentos_proyecto_proyecto'), type_='foreignkey')
        batch_op.create_foreign_key('fk_documentos_proyecto_proyecto', 'proyectos', ['proyecto_id'], ['id'], referent_schema='public', ondelete='CASCADE', use_alter=True)
        batch_op.create_foreign_key(None, 'documentos', ['documento_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_tipo_entidad_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('entidades_municipio_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'municipios', ['municipio_id'], ['id'])
        batch_op.create_foreign_key(None, 'tipos_entidades', ['tipo_entidad_id'], ['id'])

    with op.batch_alter_table('entidades_administrados', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_administrados_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('entidades_ayuntamientos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_ayuntamientos_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('entidades_diputaciones', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_diputaciones_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('entidades_empresas_servicio_publico', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_empresas_servicio_publico_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('entidades_organismos_publicos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_organismos_publicos_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('expedientes_tipo_expediente_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('expedientes_responsable_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('expedientes_proyecto_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('expedientes_titular_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['responsable_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'tipos_expedientes', ['tipo_expediente_id'], ['id'])
        batch_op.create_foreign_key(None, 'proyectos', ['proyecto_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'entidades', ['titular_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('fases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fases_documento_resultado_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fases_solicitud_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fases_tipo_fase_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fases_resultado_fase_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_fases', ['tipo_fase_id'], ['id'])
        batch_op.create_foreign_key(None, 'solicitudes', ['solicitud_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'documentos', ['documento_resultado_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'tipos_resultados_fases', ['resultado_fase_id'], ['id'])

    with op.batch_alter_table('municipios_proyecto', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('municipios_proyecto_municipio_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_municipios_proyecto_proyecto'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'municipios', ['municipio_id'], ['id'])
        batch_op.create_foreign_key('fk_municipios_proyecto_proyecto', 'proyectos', ['proyecto_id'], ['id'], referent_schema='public', ondelete='CASCADE', use_alter=True)

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('proyectos_ia_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_ia', ['ia_id'], ['id'])

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('solicitudes_solicitud_afectada_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_solicitudes_expediente'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'solicitudes', ['solicitud_afectada_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key('fk_solicitudes_expediente', 'expedientes', ['expediente_id'], ['id'], referent_schema='public', use_alter=True)

    with op.batch_alter_table('solicitudes_tipos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('solicitudes_tipos_solicitudid_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('solicitudes_tipos_tiposolicitudid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_solicitudes', ['tiposolicitudid'], ['id'])
        batch_op.create_foreign_key(None, 'solicitudes', ['solicitudid'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('tabla_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles_lectura', postgresql.ARRAY(sa.Integer()), nullable=True, comment='Array de role_id con permiso SELECT. NULL = nadie puede leer, [] = nadie, [1,2,3] = ADMIN, SUPERVISOR, TRAMITADOR'))
        batch_op.add_column(sa.Column('roles_escritura', postgresql.ARRAY(sa.Integer()), nullable=True, comment='Array de role_id con permiso INSERT+UPDATE. Debe ser subconjunto de roles_lectura'))
        batch_op.add_column(sa.Column('roles_eliminacion', postgresql.ARRAY(sa.Integer()), nullable=True, comment='Array de role_id con permiso DELETE. Debe ser subconjunto de roles_escritura'))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción del propósito y contenido de la tabla'))
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=True, comment="Categoría de la tabla: 'estructural', 'operacional', 'sistema'"))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False, comment='Fecha y hora de creación del registro'))
        batch_op.add_column(sa.Column('ultima_modificacion', sa.DateTime(), nullable=False, comment='Fecha y hora de última modificación'))
        batch_op.alter_column('nombre_tabla',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre completo de la tabla (schema.tabla o tabla). Ejemplo: public.expedientes, municipios',
               existing_comment='Nombre completo de la tabla (schema.tabla). Ejemplo: public.usuarios, expedientes.expedientes',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_tabla_metadata_nombre'))
        batch_op.drop_constraint(batch_op.f('tabla_metadata_nombre_tabla_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_public_tabla_metadata_nombre_tabla'), ['nombre_tabla'], unique=True)
        batch_op.drop_column('orden_asc')
        batch_op.drop_column('titulo_singular')
        batch_op.drop_column('roles_pueden_eliminar')
        batch_op.drop_column('campo_orden_defecto')
        batch_op.drop_column('roles_pueden_visualizar')
        batch_op.drop_column('titulo_plural')

    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tareas_documento_usado_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tareas_documento_producido_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tareas_tipo_tarea_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tareas_tramite_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'documentos', ['documento_producido_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'tramites', ['tramite_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tipos_tareas', ['tipo_tarea_id'], ['id'])
        batch_op.create_foreign_key(None, 'documentos', ['documento_usado_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('tramites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tramites_tipo_tramite_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tramites_fase_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_tramites', ['tipo_tramite_id'], ['id'])
        batch_op.create_foreign_key(None, 'fases', ['fase_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('usuarios_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_roles_usuario_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('usuarios_roles_rol_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usuarios_roles_rol_id_fkey'), 'roles', ['rol_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('usuarios_roles_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('tramites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tramites_fase_id_fkey'), 'fases', ['fase_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('tramites_tipo_tramite_id_fkey'), 'tipos_tramites', ['tipo_tramite_id'], ['id'])

    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tareas_tramite_id_fkey'), 'tramites', ['tramite_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('tareas_tipo_tarea_id_fkey'), 'tipos_tareas', ['tipo_tarea_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tareas_documento_producido_id_fkey'), 'documentos', ['documento_producido_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tareas_documento_usado_id_fkey'), 'documentos', ['documento_usado_id'], ['id'])

    with op.batch_alter_table('tabla_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo_plural', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Nombre plural para mostrar en interfaz. Ejemplo: Usuarios, Expedientes, Provincias'))
        batch_op.add_column(sa.Column('roles_pueden_visualizar', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True, comment='Array de role_id que tienen permiso para visualizar la tabla. Ejemplo: [1,2,3,4,5] = todos. NULL = usar permisos por defecto, [] = nadie puede visualizar'))
        batch_op.add_column(sa.Column('campo_orden_defecto', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Campo por defecto para ordenar listados. Ejemplo: apellido1, fecha_alta, nombre'))
        batch_op.add_column(sa.Column('roles_pueden_eliminar', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True, comment='Array de role_id que tienen permiso para eliminar registros. Ejemplo: [1,2] = ADMIN y SUPERVISOR. NULL = usar permisos por defecto, [] = nadie puede eliminar'))
        batch_op.add_column(sa.Column('titulo_singular', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Nombre singular para mostrar en interfaz. Ejemplo: Usuario, Expediente, Provincia'))
        batch_op.add_column(sa.Column('orden_asc', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Dirección del orden por defecto. TRUE=Ascendente (A-Z, 0-9, antiguos primero), FALSE=Descendente (Z-A, 9-0, recientes primero)'))
        batch_op.drop_index(batch_op.f('ix_public_tabla_metadata_nombre_tabla'))
        batch_op.create_unique_constraint(batch_op.f('tabla_metadata_nombre_tabla_key'), ['nombre_tabla'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_tabla_metadata_nombre'), ['nombre_tabla'], unique=False)
        batch_op.alter_column('nombre_tabla',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre completo de la tabla (schema.tabla). Ejemplo: public.usuarios, expedientes.expedientes',
               existing_comment='Nombre completo de la tabla (schema.tabla o tabla). Ejemplo: public.expedientes, municipios',
               existing_nullable=False)
        batch_op.drop_column('ultima_modificacion')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('categoria')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('roles_eliminacion')
        batch_op.drop_column('roles_escritura')
        batch_op.drop_column('roles_lectura')

    with op.batch_alter_table('solicitudes_tipos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solicitudes_tipos_tiposolicitudid_fkey'), 'tipos_solicitudes', ['tiposolicitudid'], ['id'])
        batch_op.create_foreign_key(batch_op.f('solicitudes_tipos_solicitudid_fkey'), 'solicitudes', ['solicitudid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_solicitudes_expediente', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_solicitudes_expediente'), 'expedientes', ['expediente_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('solicitudes_solicitud_afectada_id_fkey'), 'solicitudes', ['solicitud_afectada_id'], ['id'])

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('proyectos_ia_id_fkey'), 'tipos_ia', ['ia_id'], ['id'])

    with op.batch_alter_table('municipios_proyecto', schema=None) as batch_op:
        batch_op.drop_constraint('fk_municipios_proyecto_proyecto', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_municipios_proyecto_proyecto'), 'proyectos', ['proyecto_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('municipios_proyecto_municipio_id_fkey'), 'municipios', ['municipio_id'], ['id'])

    with op.batch_alter_table('fases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fases_resultado_fase_id_fkey'), 'tipos_resultados_fases', ['resultado_fase_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fases_tipo_fase_id_fkey'), 'tipos_fases', ['tipo_fase_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fases_solicitud_id_fkey'), 'solicitudes', ['solicitud_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fases_documento_resultado_id_fkey'), 'documentos', ['documento_resultado_id'], ['id'])

    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expedientes_titular_id_fkey'), 'entidades', ['titular_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('expedientes_proyecto_id_fkey'), 'proyectos', ['proyecto_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('expedientes_responsable_id_fkey'), 'usuarios', ['responsable_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('expedientes_tipo_expediente_id_fkey'), 'tipos_expedientes', ['tipo_expediente_id'], ['id'])

    with op.batch_alter_table('entidades_organismos_publicos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_organismos_publicos_entidad_id_fkey'), 'entidades', ['entidad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('entidades_empresas_servicio_publico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_empresas_servicio_publico_entidad_id_fkey'), 'entidades', ['entidad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('entidades_diputaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_diputaciones_entidad_id_fkey'), 'entidades', ['entidad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('entidades_ayuntamientos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_ayuntamientos_entidad_id_fkey'), 'entidades', ['entidad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('entidades_administrados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_administrados_entidad_id_fkey'), 'entidades', ['entidad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_municipio_id_fkey'), 'municipios', ['municipio_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('entidades_tipo_entidad_id_fkey'), 'tipos_entidades', ['tipo_entidad_id'], ['id'])

    with op.batch_alter_table('documentos_proyecto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_documentos_proyecto_proyecto', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_documentos_proyecto_proyecto'), 'proyectos', ['proyecto_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('documentos_proyecto_documento_id_fkey'), 'documentos', ['documento_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('documentos_expediente_id_fkey'), 'expedientes', ['expediente_id'], ['id'])

    with op.batch_alter_table('autorizados_titular', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('autorizados_titular_titular_entidad_id_fkey'), 'entidades', ['titular_entidad_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('autorizados_titular_autorizado_entidad_id_fkey'), 'entidades', ['autorizado_entidad_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
