"""Add tabla_metadata for Issue #85 - Phase 1

Revision ID: 12c75207263b
Revises: dfdeb43518d6
Create Date: 2026-02-06 19:36:18.361102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12c75207263b'
down_revision = 'dfdeb43518d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabla_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado'),
    sa.Column('nombre_tabla', sa.String(length=100), nullable=False, comment='Nombre completo de la tabla (schema.tabla). Ejemplo: public.usuarios, expedientes.expedientes'),
    sa.Column('titulo_singular', sa.String(length=100), nullable=False, comment='Nombre singular para mostrar en interfaz. Ejemplo: Usuario, Expediente, Provincia'),
    sa.Column('titulo_plural', sa.String(length=100), nullable=False, comment='Nombre plural para mostrar en interfaz. Ejemplo: Usuarios, Expedientes, Provincias'),
    sa.Column('campo_orden_defecto', sa.String(length=100), nullable=False, comment='Campo por defecto para ordenar listados. Ejemplo: apellido1, fecha_alta, nombre'),
    sa.Column('orden_asc', sa.Boolean(), nullable=False, comment='Dirección del orden por defecto. TRUE=Ascendente (A-Z, 0-9, antiguos primero), FALSE=Descendente (Z-A, 9-0, recientes primero)'),
    sa.Column('roles_pueden_eliminar', postgresql.ARRAY(sa.Integer()), nullable=True, comment='Array de role_id que tienen permiso para eliminar registros. Ejemplo: [1,2] = ADMIN y SUPERVISOR. NULL = usar permisos por defecto, [] = nadie puede eliminar'),
    sa.Column('roles_pueden_visualizar', postgresql.ARRAY(sa.Integer()), nullable=True, comment='Array de role_id que tienen permiso para visualizar la tabla. Ejemplo: [1,2,3,4,5] = todos. NULL = usar permisos por defecto, [] = nadie puede visualizar'),
    sa.CheckConstraint("campo_orden_defecto IS NOT NULL AND TRIM(campo_orden_defecto) != ''", name='chk_campo_orden_not_empty'),
    sa.CheckConstraint("nombre_tabla IS NOT NULL AND TRIM(nombre_tabla) != ''", name='chk_nombre_tabla_not_empty'),
    sa.CheckConstraint("titulo_plural IS NOT NULL AND TRIM(titulo_plural) != ''", name='chk_titulo_plural_not_empty'),
    sa.CheckConstraint("titulo_singular IS NOT NULL AND TRIM(titulo_singular) != ''", name='chk_titulo_singular_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_tabla'),
    schema='public'
    )
    with op.batch_alter_table('tabla_metadata', schema=None) as batch_op:
        batch_op.create_index('idx_tabla_metadata_nombre', ['nombre_tabla'], unique=False)

    with op.batch_alter_table('autorizados_titular', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('autorizados_titular_autorizado_entidad_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('autorizados_titular_titular_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['titular_entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'entidades', ['autorizado_entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('documentos_expediente_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'expedientes', ['expediente_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('documentos_proyecto', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('documentos_proyecto_documento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'documentos', ['documento_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_documentos_proyecto_proyecto', 'proyectos', ['proyecto_id'], ['id'], referent_schema='public', ondelete='CASCADE', use_alter=True)

    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_municipio_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('entidades_tipo_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_entidades', ['tipo_entidad_id'], ['id'])
        batch_op.create_foreign_key(None, 'municipios', ['municipio_id'], ['id'])

    with op.batch_alter_table('entidades_administrados', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_administrados_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('entidades_ayuntamientos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_ayuntamientos_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('entidades_diputaciones', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_diputaciones_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('entidades_empresas_servicio_publico', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_empresas_servicio_publico_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('entidades_organismos_publicos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entidades_organismos_publicos_entidad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entidades', ['entidad_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('expedientes_proyecto_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('expedientes_responsable_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('expedientes_tipo_expediente_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('expedientes_titular_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_expedientes', ['tipo_expediente_id'], ['id'])
        batch_op.create_foreign_key(None, 'entidades', ['titular_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'proyectos', ['proyecto_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'usuarios', ['responsable_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('fases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fases_documento_resultado_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fases_solicitud_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fases_tipo_fase_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fases_resultado_fase_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_resultados_fases', ['resultado_fase_id'], ['id'])
        batch_op.create_foreign_key(None, 'solicitudes', ['solicitud_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tipos_fases', ['tipo_fase_id'], ['id'])
        batch_op.create_foreign_key(None, 'documentos', ['documento_resultado_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('municipios_proyecto', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('municipios_proyecto_municipio_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_municipios_proyecto_proyecto', 'proyectos', ['proyecto_id'], ['id'], referent_schema='public', ondelete='CASCADE', use_alter=True)
        batch_op.create_foreign_key(None, 'municipios', ['municipio_id'], ['id'])

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('proyectos_ia_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_ia', ['ia_id'], ['id'])

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('solicitudes_solicitud_afectada_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_solicitudes_expediente', 'expedientes', ['expediente_id'], ['id'], referent_schema='public', use_alter=True)
        batch_op.create_foreign_key(None, 'solicitudes', ['solicitud_afectada_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('solicitudes_tipos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('solicitudes_tipos_solicitudid_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('solicitudes_tipos_tiposolicitudid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'solicitudes', ['solicitudid'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tipos_solicitudes', ['tiposolicitudid'], ['id'])

    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tareas_documento_producido_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tareas_tipo_tarea_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tareas_documento_usado_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tareas_tramite_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tramites', ['tramite_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'documentos', ['documento_usado_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'tipos_tareas', ['tipo_tarea_id'], ['id'])
        batch_op.create_foreign_key(None, 'documentos', ['documento_producido_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('tramites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tramites_tipo_tramite_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tramites_fase_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'fases', ['fase_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tipos_tramites', ['tipo_tramite_id'], ['id'])

    with op.batch_alter_table('usuarios_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_roles_rol_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('usuarios_roles_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usuarios_roles_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('usuarios_roles_rol_id_fkey'), 'roles', ['rol_id'], ['id'])

    with op.batch_alter_table('tramites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tramites_fase_id_fkey'), 'fases', ['fase_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('tramites_tipo_tramite_id_fkey'), 'tipos_tramites', ['tipo_tramite_id'], ['id'])

    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tareas_tramite_id_fkey'), 'tramites', ['tramite_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('tareas_documento_usado_id_fkey'), 'documentos', ['documento_usado_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tareas_tipo_tarea_id_fkey'), 'tipos_tareas', ['tipo_tarea_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tareas_documento_producido_id_fkey'), 'documentos', ['documento_producido_id'], ['id'])

    with op.batch_alter_table('solicitudes_tipos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solicitudes_tipos_tiposolicitudid_fkey'), 'tipos_solicitudes', ['tiposolicitudid'], ['id'])
        batch_op.create_foreign_key(batch_op.f('solicitudes_tipos_solicitudid_fkey'), 'solicitudes', ['solicitudid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_solicitudes_expediente', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solicitudes_solicitud_afectada_id_fkey'), 'solicitudes', ['solicitud_afectada_id'], ['id'])

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('proyectos_ia_id_fkey'), 'tipos_ia', ['ia_id'], ['id'])

    with op.batch_alter_table('municipios_proyecto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_municipios_proyecto_proyecto', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('municipios_proyecto_municipio_id_fkey'), 'municipios', ['municipio_id'], ['id'])

    with op.batch_alter_table('fases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fases_resultado_fase_id_fkey'), 'tipos_resultados_fases', ['resultado_fase_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fases_tipo_fase_id_fkey'), 'tipos_fases', ['tipo_fase_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fases_solicitud_id_fkey'), 'solicitudes', ['solicitud_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fases_documento_resultado_id_fkey'), 'documentos', ['documento_resultado_id'], ['id'])

    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expedientes_titular_id_fkey'), 'entidades', ['titular_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('expedientes_tipo_expediente_id_fkey'), 'tipos_expedientes', ['tipo_expediente_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('expedientes_responsable_id_fkey'), 'usuarios', ['responsable_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('expedientes_proyecto_id_fkey'), 'proyectos', ['proyecto_id'], ['id'])

    with op.batch_alter_table('entidades_organismos_publicos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_organismos_publicos_entidad_id_fkey'), 'entidades', ['entidad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('entidades_empresas_servicio_publico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_empresas_servicio_publico_entidad_id_fkey'), 'entidades', ['entidad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('entidades_diputaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_diputaciones_entidad_id_fkey'), 'entidades', ['entidad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('entidades_ayuntamientos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_ayuntamientos_entidad_id_fkey'), 'entidades', ['entidad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('entidades_administrados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_administrados_entidad_id_fkey'), 'entidades', ['entidad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entidades_tipo_entidad_id_fkey'), 'tipos_entidades', ['tipo_entidad_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('entidades_municipio_id_fkey'), 'municipios', ['municipio_id'], ['id'])

    with op.batch_alter_table('documentos_proyecto', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documentos_proyecto_proyecto', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('documentos_proyecto_documento_id_fkey'), 'documentos', ['documento_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('documentos_expediente_id_fkey'), 'expedientes', ['expediente_id'], ['id'])

    with op.batch_alter_table('autorizados_titular', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('autorizados_titular_titular_entidad_id_fkey'), 'entidades', ['titular_entidad_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('autorizados_titular_autorizado_entidad_id_fkey'), 'entidades', ['autorizado_entidad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tabla_metadata', schema=None) as batch_op:
        batch_op.drop_index('idx_tabla_metadata_nombre')

    op.drop_table('tabla_metadata', schema='public')
    # ### end Alembic commands ###
