"""Migración inicial limpia

Revision ID: 3daee4b13400
Revises: 
Create Date: 2026-01-28 16:42:34.046841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3daee4b13400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del municipio'),
    sa.Column('codigo', sa.String(length=10), nullable=False, comment='Código INE oficial del municipio (5 dígitos)'),
    sa.Column('nombre', sa.String(length=200), nullable=False, comment='Denominación oficial del municipio'),
    sa.Column('provincia', sa.String(length=100), nullable=False, comment='Provincia a la que pertenece el municipio'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='estructura'
    )
    op.create_table('tipos_expedientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del tipo de expediente'),
    sa.Column('tipo', sa.String(length=100), nullable=True, comment='Denominación del tipo según clasificación normativa'),
    sa.Column('descripcion', sa.String(length=200), nullable=True, comment='Descripción detallada de características y particularidades procedimentales'),
    sa.PrimaryKeyConstraint('id'),
    schema='estructura'
    )
    op.create_table('tipos_fases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del tipo de fase'),
    sa.Column('codigo', sa.String(length=50), nullable=False, comment='Código único inmutable de la fase (usado en lógica de reglas)'),
    sa.Column('nombre', sa.String(length=200), nullable=False, comment='Denominación completa de la fase para interfaz de usuario'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='estructura'
    )
    op.create_table('tipos_ia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del tipo de instrumento ambiental'),
    sa.Column('siglas', sa.String(length=10), nullable=False, comment='Código del instrumento ambiental (ver datos_maestros.sql)'),
    sa.Column('descripcion', sa.String(length=200), nullable=True, comment='Denominación completa del instrumento ambiental'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siglas'),
    schema='estructura'
    )
    op.create_table('tipos_resultados_fases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del tipo de resultado'),
    sa.Column('codigo', sa.String(length=50), nullable=False, comment='Código único inmutable del resultado (usado en lógica de reglas)'),
    sa.Column('nombre', sa.String(length=200), nullable=False, comment='Denominación completa del resultado para interfaz de usuario'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='estructura'
    )
    op.create_table('tipos_solicitudes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del tipo de solicitud'),
    sa.Column('siglas', sa.String(length=100), nullable=False, comment='Código normalizado del acto administrativo (AAP, AAC, DUP, etc.)'),
    sa.Column('descripcion', sa.String(length=200), nullable=False, comment='Descripción completa del acto administrativo solicitado'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siglas'),
    schema='estructura'
    )
    op.create_table('tipos_tareas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del tipo de tarea'),
    sa.Column('codigo', sa.String(length=50), nullable=False, comment='Código único inmutable de la tarea (usado en lógica de reglas)'),
    sa.Column('nombre', sa.String(length=200), nullable=False, comment='Denominación completa de la tarea para interfaz de usuario'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='estructura'
    )
    op.create_table('tipos_tramites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del tipo de trámite'),
    sa.Column('codigo', sa.String(length=50), nullable=False, comment='Código único inmutable del trámite (usado en lógica de reglas)'),
    sa.Column('nombre', sa.String(length=200), nullable=False, comment='Denominación completa del trámite para interfaz de usuario'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='estructura'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del rol'),
    sa.Column('nombre', sa.String(length=50), nullable=False, comment='Nombre del rol (ADMIN, SUPERVISOR, TRAMITADOR, ADMINISTRATIVO)'),
    sa.Column('descripcion', sa.String(length=200), nullable=True, comment='Descripción del propósito y permisos del rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='public'
    )
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado de la solicitud'),
    sa.Column('expediente_id', sa.Integer(), nullable=False, comment='FK a EXPEDIENTES. Expediente al que pertenece la solicitud'),
    sa.Column('solicitud_afectada_id', sa.Integer(), nullable=True, comment='FK a SOLICITUDES. Para DESISTIMIENTO/RENUNCIA, solicitud que se desiste'),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False, comment='Fecha oficial de presentación de la solicitud'),
    sa.Column('estado', sa.String(length=20), nullable=False, comment='Estado: EN_TRAMITE, RESUELTA, DESISTIDA, ARCHIVADA'),
    sa.Column('observaciones', sa.String(length=2000), nullable=True, comment='Notas o comentarios adicionales del técnico'),
    sa.ForeignKeyConstraint(['expediente_id'], ['public.expedientes.id'], name='fk_solicitudes_expediente', use_alter=True),
    sa.ForeignKeyConstraint(['solicitud_afectada_id'], ['public.solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.create_index('idx_solicitudes_estado', ['estado'], unique=False)
        batch_op.create_index('idx_solicitudes_expediente', ['expediente_id'], unique=False)
        batch_op.create_index('idx_solicitudes_fecha', ['fecha_solicitud'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del usuario'),
    sa.Column('siglas', sa.String(length=50), nullable=False, comment='Código identificativo corto del usuario (único)'),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre de pila del usuario'),
    sa.Column('apellido1', sa.String(length=50), nullable=False, comment='Primer apellido del usuario'),
    sa.Column('apellido2', sa.String(length=50), nullable=True, comment='Segundo apellido del usuario (opcional)'),
    sa.Column('email', sa.String(length=120), nullable=True, comment='Email del usuario (opcional, único si no es NULL)'),
    sa.Column('activo', sa.Boolean(), nullable=True, comment='TRUE=habilitado, FALSE=desactivado (mantiene historial)'),
    sa.Column('password_hash', sa.String(length=256), nullable=True, comment='Hash bcrypt de la contraseña (nunca almacenar en texto plano)'),
    sa.Column('reset_token', sa.String(length=100), nullable=True, comment='Token temporal para recuperación de contraseña'),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True, comment='Fecha de expiración del token de recuperación'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('siglas'),
    schema='public'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index('idx_usuarios_email', ['email'], unique=False)
        batch_op.create_index('idx_usuarios_siglas', ['siglas'], unique=False)

    op.create_table('municipios_proyecto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del registro puente'),
    sa.Column('municipio_id', sa.Integer(), nullable=False, comment='FK a MUNICIPIOS. Municipio afectado por el proyecto'),
    sa.Column('proyecto_id', sa.Integer(), nullable=False, comment='FK a PROYECTOS. Proyecto técnico que afecta al municipio'),
    sa.ForeignKeyConstraint(['municipio_id'], ['estructura.municipios.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['public.proyectos.id'], name='fk_municipios_proyecto_proyecto', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'proyecto_id', name='municipios_proyecto_municipio_proyecto_key'),
    schema='public'
    )
    with op.batch_alter_table('municipios_proyecto', schema=None) as batch_op:
        batch_op.create_index('idx_municipios_proyecto_municipio', ['municipio_id'], unique=False)
        batch_op.create_index('idx_municipios_proyecto_proyecto', ['proyecto_id'], unique=False)

    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador técnico único autogenerado'),
    sa.Column('titulo', sa.String(length=500), nullable=False, comment='Título descriptivo del proyecto técnico'),
    sa.Column('descripcion', sa.String(length=10000), nullable=False, comment='Descripción técnica detallada del proyecto (texto libre extenso)'),
    sa.Column('fecha', sa.Date(), nullable=False, comment='Fecha técnica del proyecto (firma/visado), NO fecha administrativa de presentación'),
    sa.Column('finalidad', sa.String(length=500), nullable=False, comment='Finalidad o uso previsto de la instalación eléctrica'),
    sa.Column('emplazamiento', sa.String(length=200), nullable=False, comment='Ubicación geográfica de la instalación (descripción textual)'),
    sa.Column('ia_id', sa.Integer(), nullable=True, comment='FK a TIPOS_IA. Instrumento ambiental aplicable (AAI, AAU, AAUS, CA, EXENTO)'),
    sa.ForeignKeyConstraint(['ia_id'], ['estructura.tipos_ia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.create_index('idx_proyectos_fecha', ['fecha'], unique=False)
        batch_op.create_index('idx_proyectos_ia', ['ia_id'], unique=False)

    op.create_table('solicitudes_tipos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del registro puente'),
    sa.Column('solicitudid', sa.Integer(), nullable=False, comment='FK a SOLICITUDES. Solicitud que contiene este tipo'),
    sa.Column('tiposolicitudid', sa.Integer(), nullable=False, comment='FK a TIPOS_SOLICITUDES. Tipo individual asignado a la solicitud'),
    sa.ForeignKeyConstraint(['solicitudid'], ['public.solicitudes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tiposolicitudid'], ['estructura.tipos_solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitudid', 'tiposolicitudid', name='solicitudes_tipos_solicitudid_tiposolicitudid_key'),
    schema='public'
    )
    with op.batch_alter_table('solicitudes_tipos', schema=None) as batch_op:
        batch_op.create_index('idx_solicitudes_tipos_solicitud', ['solicitudid'], unique=False)
        batch_op.create_index('idx_solicitudes_tipos_tipo', ['tiposolicitudid'], unique=False)

    op.create_table('usuarios_roles',
    sa.Column('usuario_id', sa.Integer(), nullable=False, comment='FK a USUARIOS. Usuario al que se asigna el rol'),
    sa.Column('rol_id', sa.Integer(), nullable=False, comment='FK a ROLES. Rol asignado al usuario'),
    sa.ForeignKeyConstraint(['rol_id'], ['public.roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['public.usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id'),
    schema='public'
    )
    op.create_table('expedientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador técnico único autogenerado'),
    sa.Column('numero_at', sa.Integer(), nullable=False, comment='Número administrativo del expediente (formato legacy, único en organización)'),
    sa.Column('responsable_id', sa.Integer(), nullable=False, comment='FK a USUARIOS. Tramitador asignado con permisos de gestión completa'),
    sa.Column('tipo_expediente_id', sa.Integer(), nullable=True, comment='FK a TIPOS_EXPEDIENTES. Clasificación normativa que define procedimiento'),
    sa.Column('heredado', sa.Boolean(), nullable=True, comment='TRUE si proviene del sistema anterior (datos incompletos posibles)'),
    sa.Column('proyecto_id', sa.Integer(), nullable=False, comment='FK a PROYECTOS. Relación 1:1, un expediente tiene exactamente un proyecto'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['public.proyectos.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['public.usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_expediente_id'], ['estructura.tipos_expedientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_at'),
    sa.UniqueConstraint('proyecto_id'),
    schema='public'
    )
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.create_index('idx_expedientes_numero_at', ['numero_at'], unique=False)
        batch_op.create_index('idx_expedientes_proyecto', ['proyecto_id'], unique=False)
        batch_op.create_index('idx_expedientes_responsable', ['responsable_id'], unique=False)
        batch_op.create_index('idx_expedientes_tipo', ['tipo_expediente_id'], unique=False)

    op.create_table('documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del documento'),
    sa.Column('expediente_id', sa.Integer(), nullable=False, comment='FK a EXPEDIENTES. ÚNCO FK del documento (tabla agnóstica)'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='Ruta o URL del archivo físico en sistema de archivos o repositorio'),
    sa.Column('tipo_contenido', sa.String(length=50), nullable=True, comment='Tipo MIME del archivo (ej: application/pdf)'),
    sa.Column('fecha_administrativa', sa.Date(), nullable=False, comment='Fecha con valor administrativo oficial (firma, registro, publicación)'),
    sa.Column('asunto', sa.String(length=500), nullable=True, comment='Descripción o asunto del documento'),
    sa.Column('origen', sa.String(length=100), nullable=True, comment='Procedencia del documento (EXTERNO, INTERNO, ORGANISMO_X, etc.)'),
    sa.Column('prioridad', sa.Integer(), nullable=True, comment='Nivel de prioridad o relevancia (default: 0)'),
    sa.Column('nombre_display', sa.String(length=200), nullable=True, comment='Nombre legible para mostrar en interfaz'),
    sa.Column('hash_md5', sa.String(length=32), nullable=True, comment='Hash MD5 para verificación de integridad y detección de duplicados'),
    sa.Column('observaciones', sa.String(length=2000), nullable=True, comment='Notas o comentarios adicionales del técnico'),
    sa.ForeignKeyConstraint(['expediente_id'], ['public.expedientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index('idx_documentos_expediente', ['expediente_id'], unique=False)
        batch_op.create_index('idx_documentos_fecha_administrativa', ['fecha_administrativa'], unique=False)
        batch_op.create_index('idx_documentos_hash', ['hash_md5'], unique=False)

    op.create_table('documentos_proyecto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del registro'),
    sa.Column('proyecto_id', sa.Integer(), nullable=False, comment='FK a PROYECTOS. Proyecto al que pertenece el documento'),
    sa.Column('documento_id', sa.Integer(), nullable=False, comment='FK UNIQUE a DOCUMENTOS. Un documento solo puede estar en un proyecto'),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='Tipo de documento: PRINCIPAL, MODIFICADO, REFUNDIDO, ANEXO'),
    sa.Column('observaciones', sa.String(length=500), nullable=True, comment='Notas del técnico sobre la incorporación del documento'),
    sa.ForeignKeyConstraint(['documento_id'], ['public.documentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['public.proyectos.id'], name='fk_documentos_proyecto_proyecto', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id'),
    schema='public'
    )
    with op.batch_alter_table('documentos_proyecto', schema=None) as batch_op:
        batch_op.create_index('idx_documentos_proyecto_proyecto', ['proyecto_id'], unique=False)
        batch_op.create_index('idx_documentos_proyecto_tipo', ['proyecto_id', 'tipo'], unique=False)

    op.create_table('fases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado de la fase'),
    sa.Column('solicitud_id', sa.Integer(), nullable=False, comment='FK a SOLICITUDES. Solicitud a la que pertenece la fase'),
    sa.Column('tipo_fase_id', sa.Integer(), nullable=False, comment='FK a TIPOS_FASES. Tipo de fase (ADMISIBILIDAD, CONSULTAS, etc.)'),
    sa.Column('fecha_inicio', sa.Date(), nullable=True, comment='Fecha de inicio de la fase. NULL = fase planificada no iniciada'),
    sa.Column('fecha_fin', sa.Date(), nullable=True, comment='Fecha de finalización de la fase. NULL = fase pendiente o en curso'),
    sa.Column('resultado_fase_id', sa.Integer(), nullable=True, comment='FK a TIPOS_RESULTADOS_FASES. Resultado de la fase al finalizar'),
    sa.Column('documento_resultado_id', sa.Integer(), nullable=True, comment='FK a DOCUMENTOS. Documento oficial que formaliza el resultado'),
    sa.Column('observaciones', sa.String(length=2000), nullable=True, comment='Notas o comentarios adicionales del técnico'),
    sa.ForeignKeyConstraint(['documento_resultado_id'], ['public.documentos.id'], ),
    sa.ForeignKeyConstraint(['resultado_fase_id'], ['estructura.tipos_resultados_fases.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['public.solicitudes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_fase_id'], ['estructura.tipos_fases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('fases', schema=None) as batch_op:
        batch_op.create_index('idx_fases_fechas', ['fecha_inicio', 'fecha_fin'], unique=False)
        batch_op.create_index('idx_fases_resultado', ['resultado_fase_id'], unique=False)
        batch_op.create_index('idx_fases_solicitud', ['solicitud_id'], unique=False)
        batch_op.create_index('idx_fases_tipo', ['tipo_fase_id'], unique=False)

    op.create_table('tramites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado del trámite'),
    sa.Column('fase_id', sa.Integer(), nullable=False, comment='FK a FASES. Fase a la que pertenece el trámite'),
    sa.Column('tipo_tramite_id', sa.Integer(), nullable=False, comment='FK a TIPOS_TRAMITES. Tipo de trámite'),
    sa.Column('fecha_inicio', sa.Date(), nullable=True, comment='Fecha de inicio del trámite. NULL = trámite planificado no iniciado'),
    sa.Column('fecha_fin', sa.Date(), nullable=True, comment='Fecha de finalización del trámite. NULL = trámite pendiente o en curso'),
    sa.Column('observaciones', sa.String(length=2000), nullable=True, comment='Notas o comentarios adicionales del técnico'),
    sa.ForeignKeyConstraint(['fase_id'], ['public.fases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_tramite_id'], ['estructura.tipos_tramites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('tramites', schema=None) as batch_op:
        batch_op.create_index('idx_tramites_fase', ['fase_id'], unique=False)
        batch_op.create_index('idx_tramites_fechas', ['fecha_inicio', 'fecha_fin'], unique=False)
        batch_op.create_index('idx_tramites_tipo', ['tipo_tramite_id'], unique=False)

    op.create_table('tareas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único autogenerado de la tarea'),
    sa.Column('tramite_id', sa.Integer(), nullable=False, comment='FK a TRAMITES. Trámite al que pertenece la tarea'),
    sa.Column('tipo_tarea_id', sa.Integer(), nullable=False, comment='FK a TIPOS_TAREAS. Tipo de tarea atómica (7 tipos posibles)'),
    sa.Column('documento_usado_id', sa.Integer(), nullable=True, comment='FK a DOCUMENTOS. Documento usado como input de la tarea'),
    sa.Column('documento_producido_id', sa.Integer(), nullable=True, comment='FK UNIQUE a DOCUMENTOS. Documento generado como output de la tarea'),
    sa.Column('fecha_inicio', sa.Date(), nullable=True, comment='Fecha de inicio de la tarea. NULL = tarea planificada no iniciada'),
    sa.Column('fecha_fin', sa.Date(), nullable=True, comment='Fecha de finalización de la tarea. NULL = tarea pendiente o en curso'),
    sa.Column('notas', sa.String(length=2000), nullable=True, comment='Observaciones o información adicional (plazos, referencia, remitente, etc.)'),
    sa.ForeignKeyConstraint(['documento_producido_id'], ['public.documentos.id'], ),
    sa.ForeignKeyConstraint(['documento_usado_id'], ['public.documentos.id'], ),
    sa.ForeignKeyConstraint(['tipo_tarea_id'], ['estructura.tipos_tareas.id'], ),
    sa.ForeignKeyConstraint(['tramite_id'], ['public.tramites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_producido_id'),
    schema='public'
    )
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.create_index('idx_tareas_documento_usado', ['documento_usado_id'], unique=False)
        batch_op.create_index('idx_tareas_fechas', ['fecha_inicio', 'fecha_fin'], unique=False)
        batch_op.create_index('idx_tareas_tipo', ['tipo_tarea_id'], unique=False)
        batch_op.create_index('idx_tareas_tramite', ['tramite_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_index('idx_tareas_tramite')
        batch_op.drop_index('idx_tareas_tipo')
        batch_op.drop_index('idx_tareas_fechas')
        batch_op.drop_index('idx_tareas_documento_usado')

    op.drop_table('tareas', schema='public')
    with op.batch_alter_table('tramites', schema=None) as batch_op:
        batch_op.drop_index('idx_tramites_tipo')
        batch_op.drop_index('idx_tramites_fechas')
        batch_op.drop_index('idx_tramites_fase')

    op.drop_table('tramites', schema='public')
    with op.batch_alter_table('fases', schema=None) as batch_op:
        batch_op.drop_index('idx_fases_tipo')
        batch_op.drop_index('idx_fases_solicitud')
        batch_op.drop_index('idx_fases_resultado')
        batch_op.drop_index('idx_fases_fechas')

    op.drop_table('fases', schema='public')
    with op.batch_alter_table('documentos_proyecto', schema=None) as batch_op:
        batch_op.drop_index('idx_documentos_proyecto_tipo')
        batch_op.drop_index('idx_documentos_proyecto_proyecto')

    op.drop_table('documentos_proyecto', schema='public')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index('idx_documentos_hash')
        batch_op.drop_index('idx_documentos_fecha_administrativa')
        batch_op.drop_index('idx_documentos_expediente')

    op.drop_table('documentos', schema='public')
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_index('idx_expedientes_tipo')
        batch_op.drop_index('idx_expedientes_responsable')
        batch_op.drop_index('idx_expedientes_proyecto')
        batch_op.drop_index('idx_expedientes_numero_at')

    op.drop_table('expedientes', schema='public')
    op.drop_table('usuarios_roles', schema='public')
    with op.batch_alter_table('solicitudes_tipos', schema=None) as batch_op:
        batch_op.drop_index('idx_solicitudes_tipos_tipo')
        batch_op.drop_index('idx_solicitudes_tipos_solicitud')

    op.drop_table('solicitudes_tipos', schema='public')
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_index('idx_proyectos_ia')
        batch_op.drop_index('idx_proyectos_fecha')

    op.drop_table('proyectos', schema='public')
    with op.batch_alter_table('municipios_proyecto', schema=None) as batch_op:
        batch_op.drop_index('idx_municipios_proyecto_proyecto')
        batch_op.drop_index('idx_municipios_proyecto_municipio')

    op.drop_table('municipios_proyecto', schema='public')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('idx_usuarios_siglas')
        batch_op.drop_index('idx_usuarios_email')

    op.drop_table('usuarios', schema='public')
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_index('idx_solicitudes_fecha')
        batch_op.drop_index('idx_solicitudes_expediente')
        batch_op.drop_index('idx_solicitudes_estado')

    op.drop_table('solicitudes', schema='public')
    op.drop_table('roles', schema='public')
    op.drop_table('tipos_tramites', schema='estructura')
    op.drop_table('tipos_tareas', schema='estructura')
    op.drop_table('tipos_solicitudes', schema='estructura')
    op.drop_table('tipos_resultados_fases', schema='estructura')
    op.drop_table('tipos_ia', schema='estructura')
    op.drop_table('tipos_fases', schema='estructura')
    op.drop_table('tipos_expedientes', schema='estructura')
    op.drop_table('municipios', schema='estructura')
    # ### end Alembic commands ###
