"""Añadir titular_id a expedientes

Revision ID: 9f6606d6cc3d
Revises: f6aa3dfeb81b
Create Date: 2026-02-04 09:24:22.031816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '9f6606d6cc3d'
down_revision = 'f6aa3dfeb81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # === CAMBIO PRINCIPAL: Añadir titular_id a expedientes ===
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titular_id', sa.Integer(), nullable=True, 
            comment='FK a ENTIDADES. Titular actual del expediente (snapshot del histórico). NULL = sin titular asignado (anómalo transitorio)'))
        batch_op.create_index('idx_expedientes_titular', ['titular_id'], unique=False)
        batch_op.create_foreign_key('expedientes_titular_id_fkey', 'entidades', ['titular_id'], ['id'], 
            referent_schema='public')
        batch_op.alter_column('responsable_id',
            existing_type=sa.INTEGER(),
            comment='FK a USUARIOS. Tramitador asignado con permisos de gestión completa. NULL = huérfano sin asignar',
            existing_comment='FK a USUARIOS. Tramitador asignado con permisos de gestión completa',
            existing_nullable=True)

    # === FIX: Añadir CASCADE a municipios_proyecto.proyecto_id ===
    # Detectar el nombre real de la constraint
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    fks = inspector.get_foreign_keys('municipios_proyecto', schema='public')
    
    # Buscar la FK que apunta a proyectos
    fk_name = None
    for fk in fks:
        if fk['referred_table'] == 'proyectos' and 'proyecto_id' in fk['constrained_columns']:
            fk_name = fk['name']
            break
    
    # Solo intentar modificar si existe
    if fk_name:
        with op.batch_alter_table('municipios_proyecto', schema=None) as batch_op:
            batch_op.drop_constraint(fk_name, type_='foreignkey')
            batch_op.create_foreign_key(fk_name, 'proyectos', 
                ['proyecto_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    else:
        # Si no existe, crearla directamente con CASCADE
        with op.batch_alter_table('municipios_proyecto', schema=None) as batch_op:
            batch_op.create_foreign_key('municipios_proyecto_proyecto_id_fkey', 'proyectos', 
                ['proyecto_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    # === SINCRONIZACIÓN: Actualizar tablas entidades_* al modelo correcto ===
    
    # entidades_ayuntamientos: simplificar campos
    with op.batch_alter_table('entidades_ayuntamientos', schema=None) as batch_op:
        batch_op.alter_column('codigo_dir3',
            existing_type=sa.VARCHAR(length=20),
            nullable=True,
            comment='Código DIR3 para notificaciones SIR',
            existing_comment='Código DIR3 oficial del ayuntamiento. Obligatorio para identificación única en sistemas oficiales')
        batch_op.drop_index('ix_public_entidades_ayuntamientos_codigo_ine_municipio')
        batch_op.drop_column('observaciones')
        batch_op.drop_column('codigo_ine_municipio')
        batch_op.drop_column('url_tablon_edictos')

    # entidades_diputaciones: actualizar comentarios y quitar campos obsoletos
    with op.batch_alter_table('entidades_diputaciones', schema=None) as batch_op:
        batch_op.alter_column('codigo_dir3',
            existing_type=sa.VARCHAR(length=20),
            comment='Código DIR3 oficial para notificaciones SIR como organismo consultado. Formato: 1-2 letras + 7-8 números. Ej: L01110002',
            existing_comment='Código DIR3 oficial de la diputación. Obligatorio',
            existing_nullable=False)
        batch_op.alter_column('email_publicacion_bop',
            existing_type=sa.VARCHAR(length=255),
            comment='Email para solicitar publicaciones en BOP. Ej: boletin@bopcadiz.org. Método tradicional: correo con datos pagador + texto',
            existing_comment='Email para envío de solicitudes de publicación en BOP. Dirección de contacto del servicio de publicaciones',
            existing_nullable=True)
        batch_op.alter_column('observaciones',
            existing_type=sa.TEXT(),
            comment='Notas sobre procedimientos publicación, tarifas, plataformas alternativas, contactos específicos. Ej: "Concesionaria: Asociación Prensa Cádiz"',
            existing_comment='Notas adicionales sobre la diputación. Procedimientos de publicación, plazos, contactos específicos',
            existing_nullable=True)
        batch_op.drop_index('ix_public_entidades_diputaciones_codigo_ine_municipio_sede')
        batch_op.drop_column('codigo_ine_municipio_sede')
        batch_op.drop_column('url_bop')

    # entidades_empresas_servicio_publico: añadir codigo_dir3
    with op.batch_alter_table('entidades_empresas_servicio_publico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_dir3', sa.String(length=20), nullable=True, 
            comment='Código DIR3 para notificaciones SIR (opcional, no todas las empresas tienen)'))
        batch_op.create_index('ix_public_entidades_empresas_servicio_publico_codigo_dir3', 
            ['codigo_dir3'], unique=True)
        batch_op.drop_column('codigo_cnae')
        batch_op.drop_column('observaciones')
        batch_op.drop_column('sector')
        batch_op.drop_column('nombre_comercial')

    # entidades_organismos_publicos: añadir campos temporales y ajustar
    with op.batch_alter_table('entidades_organismos_publicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legislatura', sa.String(length=50), nullable=True, 
            comment='Legislatura asociada. Ej: "2019-2023", "2023-2027"'))
        batch_op.add_column(sa.Column('fecha_desde', sa.Date(), nullable=True, 
            comment='Fecha inicio vigencia del organismo'))
        batch_op.add_column(sa.Column('fecha_hasta', sa.Date(), nullable=True, 
            comment='Fecha fin vigencia del organismo (NULL si sigue activo)'))
        batch_op.alter_column('codigo_dir3',
            existing_type=sa.VARCHAR(length=20),
            nullable=True,
            comment='Código DIR3 para notificaciones SIR/BandeJA',
            existing_comment='Código DIR3 oficial (directorio común de unidades orgánicas). Identificador único de organismo público. Obligatorio')
        batch_op.alter_column('ambito',
            existing_type=sa.VARCHAR(length=50),
            nullable=True,
            comment='Ámbito del organismo: ESTATAL, AUTONOMICO, LOCAL',
            existing_comment='Ámbito administrativo. Valores: "ESTATAL", "AUTONOMICO", "LOCAL", "EUROPEO"')
        batch_op.alter_column('tipo_organismo',
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=50),
            comment='Tipo específico: Consejería, Ministerio, Confederación, Entidad Pública, etc.',
            existing_comment='Clasificación del organismo. Ej: "Ministerio", "Consejería", "Dirección General", "Agencia", "Organismo Autónomo"',
            existing_nullable=True)
        batch_op.drop_index('ix_public_entidades_organismos_publicos_codigo_dir3')
        batch_op.create_index('ix_public_entidades_organismos_publicos_codigo_dir3', 
            ['codigo_dir3'], unique=False)
        batch_op.create_index('ix_public_entidades_organismos_publicos_ambito', 
            ['ambito'], unique=False)
        batch_op.create_index('ix_public_entidades_organismos_publicos_legislatura', 
            ['legislatura'], unique=False)
        batch_op.drop_column('observaciones')
        batch_op.drop_column('url_sede_electronica')

    # === FIX MENOR: Ajustar índice unique en entidades.cif_nif ===
    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.drop_constraint('entidades_cif_nif_key', type_='unique')
        batch_op.drop_index('ix_public_entidades_cif_nif')
        batch_op.create_index('ix_public_entidades_cif_nif', ['cif_nif'], unique=True)

    # === FIX MENOR: Índice unique en tipos_entidades.codigo ===
    with op.batch_alter_table('tipos_entidades', schema='estructura') as batch_op:
        batch_op.drop_constraint('tipos_entidades_codigo_key', type_='unique')
        batch_op.drop_index('ix_estructura_tipos_entidades_codigo')
        batch_op.create_index('ix_estructura_tipos_entidades_codigo', ['codigo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('tipos_entidades', schema='estructura') as batch_op:
        batch_op.drop_index('ix_estructura_tipos_entidades_codigo')
        batch_op.create_index('ix_estructura_tipos_entidades_codigo', ['codigo'], unique=False)
        batch_op.create_unique_constraint('tipos_entidades_codigo_key', ['codigo'])

    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.drop_index('ix_public_entidades_cif_nif')
        batch_op.create_index('ix_public_entidades_cif_nif', ['cif_nif'], unique=False)
        batch_op.create_unique_constraint('entidades_cif_nif_key', ['cif_nif'])

    with op.batch_alter_table('entidades_organismos_publicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_sede_electronica', sa.VARCHAR(length=255), 
            autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index('ix_public_entidades_organismos_publicos_legislatura')
        batch_op.drop_index('ix_public_entidades_organismos_publicos_ambito')
        batch_op.drop_index('ix_public_entidades_organismos_publicos_codigo_dir3')
        batch_op.create_index('ix_public_entidades_organismos_publicos_codigo_dir3', 
            ['codigo_dir3'], unique=True)
        batch_op.alter_column('tipo_organismo',
            existing_type=sa.String(length=50),
            type_=sa.VARCHAR(length=100),
            existing_nullable=True)
        batch_op.alter_column('ambito',
            existing_type=sa.VARCHAR(length=50),
            nullable=False)
        batch_op.alter_column('codigo_dir3',
            existing_type=sa.VARCHAR(length=20),
            nullable=False)
        batch_op.drop_column('fecha_hasta')
        batch_op.drop_column('fecha_desde')
        batch_op.drop_column('legislatura')

    with op.batch_alter_table('entidades_empresas_servicio_publico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_comercial', sa.VARCHAR(length=200), 
            autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('codigo_cnae', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_index('ix_public_entidades_empresas_servicio_publico_codigo_dir3')
        batch_op.drop_column('codigo_dir3')

    with op.batch_alter_table('entidades_diputaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_bop', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('codigo_ine_municipio_sede', sa.VARCHAR(length=5), 
            autoincrement=False, nullable=False))
        batch_op.create_index('ix_public_entidades_diputaciones_codigo_ine_municipio_sede', 
            ['codigo_ine_municipio_sede'], unique=False)

    with op.batch_alter_table('entidades_ayuntamientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_tablon_edictos', sa.VARCHAR(length=255), 
            autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('codigo_ine_municipio', sa.VARCHAR(length=5), 
            autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_public_entidades_ayuntamientos_codigo_ine_municipio', 
            ['codigo_ine_municipio'], unique=False)
        batch_op.alter_column('codigo_dir3', existing_type=sa.VARCHAR(length=20), nullable=False)

    # Restaurar FK sin CASCADE
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    fks = inspector.get_foreign_keys('municipios_proyecto', schema='public')
    fk_name = None
    for fk in fks:
        if fk['referred_table'] == 'proyectos' and 'proyecto_id' in fk['constrained_columns']:
            fk_name = fk['name']
            break
    
    if fk_name:
        with op.batch_alter_table('municipios_proyecto', schema=None) as batch_op:
            batch_op.drop_constraint(fk_name, type_='foreignkey')
            batch_op.create_foreign_key(fk_name, 'proyectos', ['proyecto_id'], ['id'])

    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_constraint('expedientes_titular_id_fkey', type_='foreignkey')
        batch_op.drop_index('idx_expedientes_titular')
        batch_op.alter_column('responsable_id',
            existing_type=sa.INTEGER(),
            comment='FK a USUARIOS. Tramitador asignado con permisos de gestión completa',
            existing_nullable=True)
        batch_op.drop_column('titular_id')

    # ### end Alembic commands ###
